# NumPy Practice Set

Practice questions based on Day 3 NumPy lecture. Each section maps to a topic covered in class. Try every question on your own before checking the lecture notes. Use the blank code cell beneath each question to write your solution.

**Setup — run this first:**

In [2]:
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 2.4.6


---
## Section 1 — Creating Arrays

**Q1.** Create a 1-D NumPy array containing the integers `5, 10, 15, 20, 25` from a Python list.

In [6]:
l = [5, 10, 15, 20, 25]
a = np.array(l)
a

array([ 5, 10, 15, 20, 25])

**Q2.** Create a 2-D array (matrix) with 3 rows and 4 columns, all filled with zeros.

In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**Q3.** Create a 4×4 array completely filled with the value `9`.

In [8]:
np.full((4,4),9)

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

**Q4.** Use `np.arange` to create an array of even numbers from 0 up to (but not including) 20.

In [19]:
# 1 approach
l = np.array([])

for i in np.arange(20):
    if i % 2 == 0:
        l = np.append(l, i)

print(l)
# 2 approach 
np.arange(0,20,2)

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

**Q5.** Use `np.linspace` to create an array of 9 evenly spaced numbers between 0 and 2 (both inclusive).

In [20]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

**Q6.** Create a 5×5 identity matrix.

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**Q7.** Using `np.random.default_rng` with seed `7`, generate a 3×4 array of random integers between 1 and 100 (inclusive of 1, exclusive of 100).

In [29]:
rng = np.random.default_rng(seed=7)
print(rng.integers(1,100,size=(3,4)))

[[94 62 68 89]
 [58 77 83 23]
 [ 6 30 29 87]]


---
## Section 2 — Array Attributes & dtypes

**Q8.** For the array `A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])`, print its `ndim`, `shape`, `size`, `dtype`, and `nbytes`.

In [31]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(A.shape)
print(A.ndim)
print(A.size)
print(A.dtype)
print(A.nbytes)

(2, 4)
2
8
int64
64


**Q9.** Create an array `[1.5, 2.7, 3.9, 4.2]` with dtype `float32`, then convert it to an integer array using `astype`. What values do you get, and why? (Add a short comment.)

In [38]:
a = np.array([1.5, 2.7, 3.9, 4.2], dtype = np.float32 )
np.astype(a,np.int64)

array([1, 2, 3, 4])

**Q10.** Create the array `[0, 1, 2, 0, 5]` and convert it to a boolean array. Predict the output before running.

In [43]:
a = np.array([0, 1, 2, 0, 5], dtype = bool)
print(a)

[False  True  True False  True]


---
## Section 3 — Indexing & Slicing

**Q11.** Create `x = np.arange(100, 110)`. Extract: (a) the first element, (b) the last element, (c) elements from index 3 to 7, (d) every 3rd element, (e) the array reversed.

In [61]:
x = np.arange(100, 110)
print(x)
print(x[0])
print(x[len(x)-1])
print(x[3:8])
print(x[::3])
print(x[::-1])

[100 101 102 103 104 105 106 107 108 109]
100
109
[103 104 105 106 107]
[100 103 106 109]
[109 108 107 106 105 104 103 102 101 100]


**Q12.** Create `M = np.arange(1, 21).reshape(4, 5)`. Print the matrix, then extract:
- (a) the element at row 2, column 3
- (b) the entire second row
- (c) the entire third column
- (d) the sub-matrix consisting of the first 2 rows and last 3 columns
- (e) the last row

In [4]:
M = np.arange(1, 21).reshape(4, 5)
print(M)
print(M[:,2])
print(M[3,:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 3  8 13 18]
[16 17 18 19 20]


**Q13.** From `M` above, extract every alternate row (rows 0, 2).

In [5]:
print(M[0:4:2])

[[ 1  2  3  4  5]
 [11 12 13 14 15]]


---
## Section 4 — Vectorized Operations (ufuncs)

**Q14.** Given `a = np.array([2, 4, 6, 8])` and `b = np.array([1, 3, 5, 7])`, compute element-wise: `a + b`, `a - b`, `a * b`, `a / b`, and `a ** 2`.

In [7]:
a = np.array([2, 4, 6, 8])
b = np.array([1, 3, 5, 7])
print(a + b, a - b, a * b, a / b, a ** 2)

[ 3  7 11 15] [1 1 1 1] [ 2 12 30 56] [2.         1.33333333 1.2        1.14285714] [ 4 16 36 64]


**Q15.** Compute the square root and natural logarithm of the array `[1, 4, 9, 16, 25]` using NumPy ufuncs.

In [58]:
a = np.array([1, 4, 9, 16, 25])
print(np.sqrt(a))
print(np.log(a))

[1. 2. 3. 4. 5.]
[0.         1.38629436 2.19722458 2.77258872 3.21887582]


**Q16.** Compute the dot product of `a = [1, 2, 3]` and `b = [4, 5, 6]` using the `@` operator.

In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a @ b

np.int64(32)

**Q17.** Speed test: use `%timeit` to compare cubing 500,000 numbers using a Python list comprehension vs a NumPy array.

In [14]:
l = list(range(0,500000))
%timeit [x ** 3 for x in l]

83.2 ms ± 4.01 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


---
## Section 5 — Broadcasting

**Q18.** Add the scalar `100` to the array `[1, 2, 3, 4, 5]`.

In [3]:
arr =np.array([1,2,3,4,5])
result = arr + 100
print(result)

[101 102 103 104 105]


**Q19.** Add the 1-D array `[1, 2, 3]` to every row of the 2-D array `[[10, 20, 30], [40, 50, 60], [70, 80, 90]]`.

In [4]:
arr_2 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
arr_1 = np.array([1, 2, 3])

result = arr_2 + arr_1
print(result)


[[11 22 33]
 [41 52 63]
 [71 82 93]]


**Q20.** Create a column vector `[[1], [2], [3], [4]]` (shape `(4,1)`) and add it to the row vector `[10, 20, 30]` (shape `(3,)`). What is the resulting shape? Why?

In [6]:
col_vec = np.array([[1], [2], [3], [4]])  
row_vec = np.array([10, 20, 30])        

result = col_vec + row_vec
print("Result:", result)
print("Resulting Shape:", result.shape)

Result: [[11 21 31]
 [12 22 32]
 [13 23 33]
 [14 24 34]]
Resulting Shape: (4, 3)


**Q21.** Try adding a `(2, 3)` array and a `(4,)` array. Catch the `ValueError` with try/except and print the error message. Explain in a comment why broadcasting fails here.

In [8]:
arr_a = np.ones((2, 3))
arr_b = np.ones((4,))

try:
    result = arr_a + arr_b
except ValueError:
    print(f"could not be broadcast together with shapes (2,3) (4,)")

could not be broadcast together with shapes (2,3) (4,)


---
## Section 6 — Aggregations & the `axis` Argument

**Q22.** Given
```python
M = np.array([[3, 7, 2, 8],
              [5, 1, 9, 4],
              [6, 0, 3, 2]])
```
Compute:
- (a) total sum of all elements
- (b) sum of each column
- (c) sum of each row
- (d) maximum of each row
- (e) minimum of each column

In [14]:
M = np.array([[3, 7, 2, 8],
              [5, 1, 9, 4],
              [6, 0, 3, 2]])
print("Total sum :",M.sum())
print("Total sum column :",M.sum(axis=0))
print("Total sum row:",M.sum(axis = 1))
print("maximum of each row :",M.max(axis = 1))
print("minimum of each row :",M.min(axis = 0))

Total sum : 50
Total sum column : [14  8 14 14]
Total sum row: [20 19 11]
maximum of each row : [8 9 6]
minimum of each row : [3 0 2 2]


**Q23.** For the same matrix `M`, find the index of the maximum element in each column using `argmax`.

In [15]:
max_index_col = M.argmax(axis=0)
print("Index of max element in each column:", max_index_col)

Index of max element in each column: [2 0 1 0]


**Q24.** Compute the overall mean and standard deviation of `M`, rounded to 2 decimal places.

In [16]:
mean_val = np.round(M.mean(), 2)
std_val = np.round(M.std(), 2)

print(f"Overall Mean: {mean_val}")
print(f"Overall Std Dev: {std_val}")

Overall Mean: 4.17
Overall Std Dev: 2.73


**Q25.** Compute the cumulative sum (`cumsum`) of `np.arange(1, 11)`.

In [18]:
arr = np.arange(1, 11)
cum_sum = arr.cumsum()
print("Cumulative sum:", cum_sum)

Cumulative sum: [ 1  3  6 10 15 21 28 36 45 55]


---
## Section 7 — Mini Challenges 🚀

**Q26.** Create a 5×5 matrix where each element `M[i, j] = i + j` — without using a Python `for` loop. (Hint: broadcasting a column vector with a row vector.)

In [19]:
i = np.arange(5).reshape(5, 1) 
j = np.arange(5)               

M_ij = i + j
print(M_ij)

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


**Q27.** Generate a 1-D array of 20 random numbers drawn from a standard normal distribution (seed = 0). Then compute its mean, std, min, and max.

In [37]:
rng = np.random.default_rng(seed=0)
rand_arr = rng.standard_normal(20)
print(rand_arr.mean())
print(rand_arr.std())
print(rand_arr.min())
print(rand_arr.max())

-0.18317831742872684
0.8508756897642668
-2.3250307746388343
1.3040000451301372


**Q28.** Normalize the columns of a 4×3 random matrix so that each column has mean 0 and standard deviation 1. (Use broadcasting — no loops.)

In [51]:
rng = np.random.default_rng(seed=42)
X = rng.random((4, 3))

col_mean = X.mean(axis=0)
col_std = X.std(axis=0)
X_nor = (X -col_mean)/col_std
print(X_nor)
print("new mean",X_nor.mean(axis=0))
print("new std",X_nor.std(axis=0))

[[ 0.79131531  0.06654521  0.39451346]
 [ 0.20430303 -1.33221893  0.73317712]
 [ 0.69308386  1.47539234 -1.71947659]
 [-1.6887022  -0.20971862  0.59178602]]
new mean [0.0000000e+00 1.5959456e-16 0.0000000e+00]
new std [1. 1. 1.]


**Q29.** Given marks of 5 students in 3 subjects:
```python
marks = np.array([[78, 82, 90],
                  [65, 70, 72],
                  [88, 95, 92],
                  [54, 60, 58],
                  [80, 85, 87]])
```
Find: (a) each student's average, (b) each subject's average, (c) the index of the top-scoring student overall (highest total), (d) the subject in which the class performed best on average.

In [56]:
marks = np.array([[78, 82, 90],
                  [65, 70, 72],
                  [88, 95, 92],
                  [54, 60, 58],
                  [80, 85, 87]])
avg = marks.mean(axis=1)
print(np.round(avg,2))
subject_avg = marks.mean(axis=0)
print(np.round(subject_avg,2))
student_totals = marks.sum(axis=1)
top_student_idx = student_totals.argmax()
print(student_totals,top_student_idx)

[83.33 69.   91.67 57.33 84.  ]
[73.  78.4 79.8]
[250 207 275 172 252] 2


**Q30.** Create a 10×10 multiplication table (where `M[i, j] = (i+1) * (j+1)`) using broadcasting only.

In [57]:
rows = np.arange(1, 11).reshape(10, 1) 
cols = np.arange(1, 11) 

multiplication_table = rows * cols
print(multiplication_table)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
