# NUMPY

In [39]:
import numpy as np
import random

In [7]:
big_list = list(range(100000))
big_array = np.arange(100000)

In [8]:
%timeit [x ** 2 for x in big_list]

8.57 ms ± 260 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
%timeit big_array ** 2

116 μs ± 4.38 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


### CREATING ARRAY

In [14]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [18]:
a = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6],[2,3,5,6,7,8]])
print(a)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [2 3 5 6 7 8]]


In [20]:
a = np.array([0,0,0,0])
print(a)

[0 0 0 0]


In [24]:
zero = np.zeros((2,10))
print(zero)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [27]:
print(np.ones((2,5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [29]:
print(np.full((2,6),9))

[[9 9 9 9 9 9]
 [9 9 9 9 9 9]]


In [30]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [33]:
print(np.eye(3)) #identity matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [42]:
rng = np.random.default_rng(seed=42)
print(rng.random((2,3)))

[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]]


In [46]:
print(rng.integers(1,10,size=(3,3)))

[[7 7 8]
 [5 2 8]
 [5 5 4]]


In [47]:
print(rng.normal(loc=0, scale = 1,size = 5))

[ 0.77779194  0.0660307   1.12724121  0.46750934 -0.85929246]


### Array Attributes and Data types

In [49]:
M = np.array([[1,2,3],[4,5,6]])
M

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
print(M.ndim)

2


In [51]:
print(M.shape)

(2, 3)


In [52]:
print(M.size)

6


In [54]:
print(M.dtype)

int64


In [62]:
ints = np.array([1,2,3], dtype=np.int32)

In [63]:
print(ints)

[1 2 3]


In [64]:
ints.dtype

dtype('int32')

In [66]:
ints = np.array([1,2,3], dtype=np.float64)
ints.dtype

dtype('float64')

### INDEXING AND SLICING

In [70]:
x = np.arange(10,20)
print(x)

[10 11 12 13 14 15 16 17 18 19]


In [71]:
print(x[2])

12


In [80]:
M = np.array([[1,2,3,4],[3,4,5,6]])
n = np.arange(1,13).reshape(3,4)
print(M)
print(n)

[[1 2 3 4]
 [3 4 5 6]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [82]:
print(M[1])
print(M[0][3])

[3 4 5 6]
4


# BROADCASTING

In [88]:
aa = np.array([1,2,3,4])
ba = np.array([10,20,30,40])
print(a + b)
print(a - b)
print(a * b)

[[ 4  6  8 10]
 [ 8 10 12 14]]
[[-2 -2 -2 -2]
 [ 2  2  2  2]]
[[ 3  8 15 24]
 [15 24 35 48]]


In [89]:
a = np.array([[1,2,3,4],
              [5,6,7,8]])

In [94]:
b = np.array([3,4,5,6])

In [95]:
print(a+b)

[[ 4  6  8 10]
 [ 8 10 12 14]]
